<?php

declare(strict_types=1);

namespace App\Storefront\Hero;

use Symfony\Component\DependencyInjection\Attribute\AutoconfigureTag;

/**
 * Provides data for the homepage hero, never markup.
 *
 * Contributors run by descending priority (#[AsTaggedItem(priority: ...)]),
 * each one receiving the content built so far.
 *
 * Generated by sylius-starter/core: do not edit.
 */
#[AutoconfigureTag(self::TAG)]
interface HeroContributorInterface
{
    public const TAG = 'app.storefront.hero_contributor';

    public function contribute(HeroContent $hero): HeroContent;
}
