<?php

declare(strict_types=1);

namespace App\Storefront\Hero;

/**
 * Data displayed by the homepage hero.
 *
 * Every field is optional: a theme template falls back on its own copy for
 * anything no contributor provided.
 *
 * Generated by sylius-starter/core: do not edit, add a contributor instead.
 */
final readonly class HeroContent
{
    public function __construct(
        public ?string $eyebrow = null,
        public ?string $title = null,
        public ?string $lead = null,
        public ?string $ctaLabel = null,
        public ?string $ctaUrl = null,
        public ?string $image = null,
        public ?string $imageAlt = null,
    ) {}

    /**
     * Returns a copy where the non-null values of $other replace the current ones.
     */
    public function merge(self $other): self
    {
        return new self(
            eyebrow: $other->eyebrow ?? $this->eyebrow,
            title: $other->title ?? $this->title,
            lead: $other->lead ?? $this->lead,
            ctaLabel: $other->ctaLabel ?? $this->ctaLabel,
            ctaUrl: $other->ctaUrl ?? $this->ctaUrl,
            image: $other->image ?? $this->image,
            imageAlt: $other->imageAlt ?? $this->imageAlt,
        );
    }

    public function isEmpty(): bool
    {
        return null === $this->eyebrow
            && null === $this->title
            && null === $this->lead
            && null === $this->ctaLabel
            && null === $this->image;
    }
}
