<?php

declare(strict_types=1);

namespace App\Twig\Components;

use App\Storefront\Hero\HeroContent;
use App\Storefront\Hero\HeroContributorInterface;
use Sylius\TwigHooks\Twig\Component\HookableComponentTrait;
use Symfony\Component\DependencyInjection\Attribute\AutowireIterator;
use Symfony\UX\TwigComponent\Attribute\AsTwigComponent;
use Symfony\UX\TwigComponent\Attribute\ExposeInTemplate;
use Twig\Environment;

/**
 * Homepage hero slot.
 *
 * - data comes from HeroContributorInterface services (import, project code...);
 * - markup comes from the "template" prop if set, otherwise from the active
 *   theme (THEME_TEMPLATE), otherwise from DEFAULT_TEMPLATE.
 *
 * Generated by sylius-starter/core: do not edit.
 */
#[AsTwigComponent('StorefrontHero', template: 'storefront/hero/component.html.twig')]
final class StorefrontHero
{
    use HookableComponentTrait;

    public const THEME_TEMPLATE = 'shop/homepage/hero.html.twig';

    public const DEFAULT_TEMPLATE = 'storefront/hero/default.html.twig';

    public ?string $template = null;

    private ?HeroContent $content = null;

    /**
     * @param iterable<HeroContributorInterface> $contributors
     */
    public function __construct(
        #[AutowireIterator(HeroContributorInterface::TAG)]
        private readonly iterable $contributors,
        private readonly Environment $twig,
    ) {}

    #[ExposeInTemplate('hero')]
    public function getContent(): HeroContent
    {
        if (null !== $this->content) {
            return $this->content;
        }

        $content = new HeroContent();

        foreach ($this->contributors as $contributor) {
            $content = $contributor->contribute($content);
        }

        return $this->content = $content;
    }

    #[ExposeInTemplate('hero_template')]
    public function getResolvedTemplate(): string
    {
        if (null !== $this->template) {
            return $this->template;
        }

        return $this->twig->getLoader()->exists(self::THEME_TEMPLATE)
            ? self::THEME_TEMPLATE
            : self::DEFAULT_TEMPLATE;
    }
}
